services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - /home/raspi/.config/jellyfin:/config
      - /home/raspi/HomeServer/.cache:/cache
      - /media/raspi/WD_BLACK/media:/media
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  portfolio:
    build: ./portfolio
    container_name: portfolio
    ports:
      - 8000:8000
    restart: 'unless-stopped'
  
  nginx:
    image: nginx:1-alpine
    container_name: nginx
    ports:
      - "443:443" 
    volumes:
      - /home/raspi/HomeServer/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/log/nginx:/var/log/nginx
    restart: 'unless-stopped'
    depends_on:
    - jellyfin
    - portfolio
