events {
  worker_connections 1024;
}
http {
  server {
    listen 443 ssl;
    listen 80;
    server_name nicholasmirigliani.com  www.nicholasmirigliani.com;
    
    ssl_certificate /etc/ssl/ssl_certificate;
    ssl_certificate_key /etc/ssl/ssl_certificate_key;

    location / {
      proxy_pass http://portfolio:8000;
    }
  }

  server {
    listen 443 ssl;
    listen 80;
    server_name pnfsotd.com www.pnfsotd.com;
    
    ssl_certificate /etc/ssl/pnfcert;
    ssl_certificate_key /etc/ssl/pnfcert_key;

    location / {
      proxy_pass http://pnf:5555;
    }
  }
  
}
