events {
  worker_connections 1024;
}
http {
  server {
    listen 443 ssl;
    server_name nicholasmirigliani.com  www.nicholasmirigliani.com;
    
    ssl_certificate ./ssl_certificate;
    ssl_certificate_key ./ssl_certificate_key;

    location / {
      proxy_pass http://portfolio:8000;
    }
  }
}
