events {
  worker_connections 1024;
}
http {
  server {
    listen 443 ssl;
    listen 80;
    server_name nicholasmirigliani.com  www.nicholasmirigliani.com;
    
    ssl_certificate /etc/ssl/ssl_certificate;
    ssl_certificate_key /etc/ssl/ssl_certificate_key;

    location / {
      proxy_pass http://portfolio:8000;
    }
  }
}
